### ISSUE TITLE
Compilation error with MongoDB 3.5.2

### ISSUE THREAD

**Issue by KFilipek** [pmem/pmse#26]
New MongoDB cause build break with PMSE. 

Commit ID: 1346352ff66b163fb010a270d1826c18699f3b36

Log:
`Compiling build/opt/mongo/db/commands/index_filter_commands_test.o
Compiling build/opt/mongo/db/modules/pmse/pmse_init.o
In file included from src/mongo/db/modules/pmse/pmse_init.cpp:33:0:
src/mongo/db/modules/pmse/pmse_engine.h:43:43: fatal error: mongo/db/storage/kv/kv_engine.h: No such file or directory
compilation terminated.
Linking build/opt/mongo/db/commands/list_collections_filter_test
Generating placeholder library build/opt/mongo/db/query/libquery_test_service_context.a
Skipping ranlib for build/opt/mongo/db/query/libquery_test_service_context.a
Compiling build/opt/mongo/db/modules/pmse/pmse_engine.o
scons: *** [build/opt/mongo/db/modules/pmse/pmse_init.o] Error 1
Compiling build/opt/mongo/db/modules/pmse/pmse_record_store.o
src/mongo/db/modules/pmse/pmse_engine.cpp:36:34: fatal error: mongo/platform/basic.h: No such file or directory
compilation terminated.
scons: *** [build/opt/mongo/db/modules/pmse/pmse_engine.o] Error 1
src/mongo/db/modules/pmse/pmse_record_store.cpp:35:43: fatal error: mongo/db/storage/record_store.h: No such file or directory
compilation terminated.
scons: *** [build/opt/mongo/db/modules/pmse/pmse_record_store.o] Error 1
scons: building terminated because of errors.
build/opt/mongo/db/modules/pmse/pmse_init.o failed: Error 1
build/opt/mongo/db/modules/pmse/pmse_engine.o failed: Error 1
build/opt/mongo/db/modules/pmse/pmse_record_store.o failed: Error 1
`

**Comment by acmorrow** [comment]
FYI this is almost certainly a side effect of https://jira.mongodb.org/browse/SERVER-27497

**Comment by KFilipek** [comment]
@acmorrow Thanks, adding line below solves the problem.
`env.InjectMongoIncludePaths()`

**Comment by luwei1990** [comment]
Skipping ranlib for thin archive build/opt/mongo/db/query/collation/libcollator_interface.a
Generating library build/opt/mongo/db/libserver_options_servers.a
Skipping ranlib for thin archive build/opt/mongo/db/libserver_options_servers.a
Compiling build/opt/third_party/wiredtiger/src/conn/conn_stat.o
Compiling build/opt/third_party/IntelRDFPMathLib20U1/LIBRARY/float128/dpml_ux_ops.o
Compiling build/opt/mongo/executor/network_interface_tl.o
In file included from src/mongo/transport/session.h:38:0,
                 from src/mongo/db/service_context.h:46,
                 from src/mongo/client/async_client.h:33,
                 from src/mongo/executor/network_interface_tl.h:33,
                 from src/mongo/executor/network_interface_tl.cpp:33:
src/mongo/util/future.h: In substitution of 'template<class Func, class RawResult, class, class UnwrappedResult> mongo::future_details::Future<UnwrappedResult> mongo::future_details::Future<T>::then(Func&&) && [with Func = mongo::executor::NetworkInterfaceTL::startCommand(const mongo::executor::TaskExecutor::CallbackHandle&, mongo::executor::RemoteCommandRequest&, const RemoteCommandCompletionFn&, const BatonHandle&)::<lambda()>::<lambda()>; RawResult = mongo::future_details::Future<std::unique_ptr<mongo::executor::ConnectionPool::ConnectionInterface, mongo::executor::ConnectionPool::ConnectionHandleDeleter> >; <template-parameter-1-3> = <missing>; UnwrappedResult = <missing>]':
src/mongo/util/future.h:1243:62:   required from 'auto mongo::future_details::Future<void>::then(Func&&) && [with Func = mongo::executor::NetworkInterfaceTL::startCommand(const mongo::executor::TaskExecutor::CallbackHandle&, mongo::executor::RemoteCommandRequest&, const RemoteCommandCompletionFn&, const BatonHandle&)::<lambda()>::<lambda()>]'
src/mongo/util/future.h:1304:67:   required from 'auto mongo::makeReadyFutureWith(Func&&) [with Func = mongo::executor::NetworkInterfaceTL::startCommand(const mongo::executor::TaskExecutor::CallbackHandle&, mongo::executor::RemoteCommandRequest&, const RemoteCommandCompletionFn&, const BatonHandle&)::<lambda()>::<lambda()>]'
src/mongo/executor/network_interface_tl.cpp:204:91:   required from here
src/mongo/util/future.h:857:15: internal compiler error: in instantiate_decl, at cp/pt.c:20294
               typename = std::enable_if_t<isFuture<RawResult>>,
               ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
Preprocessed source stored into /tmp/ccswiqBu.out file, please attach this to your bugreport.
scons: *** [build/opt/mongo/executor/network_interface_tl.o] Error 1
scons: building terminated because of errors.
build/opt/mongo/executor/network_interface_tl.o failed: Error 1


can anyone help me while build mongodb on aarch64

**Comment by KFilipek** [comment]
It looks like problem with MongoDB compilation, not MongoDB+PMSE, so you should ask on MongoDB forum. Make sure you use proper GCC version and you have installed all dependencies (like pip requirements):
[Build MongoDB from source](https://github.com/mongodb/mongo/wiki/Build-Mongodb-From-Source)

**Comment by acmorrow** [comment]
@luwei1990 - It looks like your compiler crashed. with an "internal compiler error", which isn't a problem with the mongodb source code, but with your toolchain. Try upgrading or patching your toolchain to latest.
